remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Kumari Natasha Bhuyan]
description: [I'm a developer with knowledge in Core Java, Python, and Web Development, focused on building responsive websites and continuously improving my programming skills.]
